# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exchange1.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1040, 597)
        Dialog.setStyleSheet("")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(30, 70, 151, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(30, 120, 151, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 0, 531, 41))
        self.label.setStyleSheet("font: 26pt \"Georgia\";")
        self.label.setObjectName("label")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(220, 70, 131, 21))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(140, 160, 113, 41))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(220, 120, 131, 21))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 280, 331, 41))
        self.label_2.setStyleSheet("font: 25pt \"Georgia\";")
        self.label_2.setObjectName("label_2")
        self.comboBox_3 = QtWidgets.QComboBox(Dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(20, 360, 151, 31))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_4 = QtWidgets.QComboBox(Dialog)
        self.comboBox_4.setGeometry(QtCore.QRect(20, 430, 151, 31))
        self.comboBox_4.setObjectName("comboBox_4")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 50, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 100, 71, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 330, 81, 16))
        self.label_5.setObjectName("label_5")
        self.comboBox_5 = QtWidgets.QComboBox(Dialog)
        self.comboBox_5.setGeometry(QtCore.QRect(250, 360, 151, 31))
        self.comboBox_5.setObjectName("comboBox_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(250, 330, 71, 20))
        self.label_6.setObjectName("label_6")
        self.comboBox_6 = QtWidgets.QComboBox(Dialog)
        self.comboBox_6.setGeometry(QtCore.QRect(250, 430, 151, 31))
        self.comboBox_6.setObjectName("comboBox_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(20, 400, 81, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(250, 400, 60, 16))
        self.label_8.setObjectName("label_8")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 470, 141, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(840, 170, 161, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(680, 170, 161, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(220, 50, 60, 16))
        self.label_10.setObjectName("label_10")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(630, 0, 321, 41))
        self.label_16.setStyleSheet("font: 25pt \"Georgia\";")
        self.label_16.setObjectName("label_16")
        self.comboBox_11 = QtWidgets.QComboBox(Dialog)
        self.comboBox_11.setGeometry(QtCore.QRect(520, 80, 151, 31))
        self.comboBox_11.setObjectName("comboBox_11")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(520, 60, 81, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(520, 110, 81, 16))
        self.label_18.setObjectName("label_18")
        self.comboBox_12 = QtWidgets.QComboBox(Dialog)
        self.comboBox_12.setGeometry(QtCore.QRect(520, 130, 151, 31))
        self.comboBox_12.setObjectName("comboBox_12")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(520, 170, 161, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.comboBox_15 = QtWidgets.QComboBox(Dialog)
        self.comboBox_15.setGeometry(QtCore.QRect(840, 130, 161, 31))
        self.comboBox_15.setObjectName("comboBox_15")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(840, 110, 71, 16))
        self.label_23.setObjectName("label_23")
        self.comboBox_16 = QtWidgets.QComboBox(Dialog)
        self.comboBox_16.setGeometry(QtCore.QRect(840, 80, 161, 31))
        self.comboBox_16.setObjectName("comboBox_16")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(840, 60, 71, 16))
        self.label_24.setObjectName("label_24")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(680, 230, 161, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.comboBox_13 = QtWidgets.QComboBox(Dialog)
        self.comboBox_13.setGeometry(QtCore.QRect(680, 80, 151, 31))
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_14 = QtWidgets.QComboBox(Dialog)
        self.comboBox_14.setGeometry(QtCore.QRect(680, 131, 151, 31))
        self.comboBox_14.setObjectName("comboBox_14")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(680, 60, 61, 16))
        self.label_9.setObjectName("label_9")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(680, 110, 61, 16))
        self.label_19.setObjectName("label_19")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(610, 280, 311, 51))
        self.label_11.setStyleSheet("font:24pt \"Georgia\";")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(520, 330, 71, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(520, 400, 61, 20))
        self.label_13.setObjectName("label_13")
        self.comboBox_7 = QtWidgets.QComboBox(Dialog)
        self.comboBox_7.setGeometry(QtCore.QRect(520, 360, 141, 31))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_8 = QtWidgets.QComboBox(Dialog)
        self.comboBox_8.setGeometry(QtCore.QRect(520, 430, 141, 31))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_9 = QtWidgets.QComboBox(Dialog)
        self.comboBox_9.setGeometry(QtCore.QRect(800, 360, 141, 31))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_10 = QtWidgets.QComboBox(Dialog)
        self.comboBox_10.setGeometry(QtCore.QRect(800, 430, 141, 31))
        self.comboBox_10.setObjectName("comboBox_10")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(800, 330, 81, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(800, 400, 81, 16))
        self.label_15.setObjectName("label_15")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(670, 470, 121, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.textEdit_3 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_3.setGeometry(QtCore.QRect(673, 530, 121, 31))
        self.textEdit_3.setObjectName("textEdit_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Calculate Current Exchange Rate"))
        self.pushButton.setText(_translate("Dialog", "Calculate"))
        self.label_2.setText(_translate("Dialog", "Graphic Visualization"))
        self.label_3.setText(_translate("Dialog", "Currency 1:"))
        self.label_4.setText(_translate("Dialog", "Currency 2:"))
        self.label_5.setText(_translate("Dialog", "Currency 1:"))
        self.label_6.setText(_translate("Dialog", "Start Year:"))
        self.label_7.setText(_translate("Dialog", "Currency 2:"))
        self.label_8.setText(_translate("Dialog", "End Year:"))
        self.pushButton_2.setText(_translate("Dialog", "Graph  Data"))
        self.pushButton_3.setText(_translate("Dialog", "Graph Related Data"))
        self.pushButton_4.setText(_translate("Dialog", "Calculate Correlation"))
        self.label_10.setText(_translate("Dialog", "Amount:"))
        self.label_16.setText(_translate("Dialog", "Calculate Correlation"))
        self.label_17.setText(_translate("Dialog", "Currency 1:"))
        self.label_18.setText(_translate("Dialog", "Currency 2:"))
        self.pushButton_7.setText(_translate("Dialog", "Graph Data"))
        self.label_23.setText(_translate("Dialog", "End Year:"))
        self.label_24.setText(_translate("Dialog", "Start Year:"))
        self.label_9.setText(_translate("Dialog", "Currency 3"))
        self.label_19.setText(_translate("Dialog", "Currency 4"))
        self.label_11.setText(_translate("Dialog", "Volatility of Currency"))
        self.label_12.setText(_translate("Dialog", "Currency 1:"))
        self.label_13.setText(_translate("Dialog", "Currency 2:"))
        self.label_14.setText(_translate("Dialog", "Start Year:"))
        self.label_15.setText(_translate("Dialog", "End Year:"))
        self.pushButton_5.setText(_translate("Dialog", "Calculate Volatility"))

