# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(966, 699)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(270, 10, 401, 41))
        self.label.setStyleSheet("font: 36pt \".SF NS Text\";\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 80, 431, 41))
        self.label_2.setStyleSheet("font: 25pt \".SF NS Text\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(110, 119, 81, 21))
        self.label_3.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(110, 140, 91, 31))
        self.comboBox.setObjectName("comboBox")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(110, 170, 101, 21))
        self.label_4.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.label_4.setObjectName("label_4")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(110, 190, 91, 32))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_3 = QtWidgets.QComboBox(Dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(110, 240, 91, 32))
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(110, 220, 101, 21))
        self.label_5.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(220, 150, 151, 31))
        self.pushButton.setObjectName("pushButton")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(240, 210, 101, 21))
        self.label_6.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.label_6.setObjectName("label_6")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(240, 230, 101, 21))
        self.textEdit.setObjectName("textEdit")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(20, 350, 431, 41))
        self.label_7.setStyleSheet("font: 25pt \".SF NS Text\";")
        self.label_7.setObjectName("label_7")
        self.comboBox_4 = QtWidgets.QComboBox(Dialog)
        self.comboBox_4.setGeometry(QtCore.QRect(120, 470, 91, 32))
        self.comboBox_4.setObjectName("comboBox_4")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(120, 450, 101, 21))
        self.label_8.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(120, 500, 101, 21))
        self.label_9.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(120, 399, 81, 21))
        self.label_10.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.label_10.setObjectName("label_10")
        self.comboBox_5 = QtWidgets.QComboBox(Dialog)
        self.comboBox_5.setGeometry(QtCore.QRect(120, 420, 91, 31))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_6 = QtWidgets.QComboBox(Dialog)
        self.comboBox_6.setGeometry(QtCore.QRect(120, 520, 91, 32))
        self.comboBox_6.setObjectName("comboBox_6")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 460, 141, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(490, 80, 431, 41))
        self.label_11.setStyleSheet("font: 25pt \".SF NS Text\";")
        self.label_11.setObjectName("label_11")
        self.comboBox_7 = QtWidgets.QComboBox(Dialog)
        self.comboBox_7.setGeometry(QtCore.QRect(570, 240, 91, 32))
        self.comboBox_7.setObjectName("comboBox_7")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(570, 220, 101, 21))
        self.label_12.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(570, 270, 101, 21))
        self.label_13.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(570, 119, 81, 21))
        self.label_14.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.label_14.setObjectName("label_14")
        self.comboBox_8 = QtWidgets.QComboBox(Dialog)
        self.comboBox_8.setGeometry(QtCore.QRect(570, 140, 91, 31))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_9 = QtWidgets.QComboBox(Dialog)
        self.comboBox_9.setGeometry(QtCore.QRect(570, 290, 91, 32))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_10 = QtWidgets.QComboBox(Dialog)
        self.comboBox_10.setGeometry(QtCore.QRect(570, 190, 91, 31))
        self.comboBox_10.setObjectName("comboBox_10")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(570, 170, 81, 21))
        self.label_15.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.label_15.setObjectName("label_15")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(680, 130, 161, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(690, 190, 141, 20))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(690, 170, 101, 21))
        self.label_16.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.label_16.setObjectName("label_16")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(680, 240, 151, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(680, 290, 161, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.comboBox_11 = QtWidgets.QComboBox(Dialog)
        self.comboBox_11.setGeometry(QtCore.QRect(550, 460, 91, 31))
        self.comboBox_11.setObjectName("comboBox_11")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(550, 440, 81, 21))
        self.label_17.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(550, 540, 101, 21))
        self.label_18.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(550, 490, 101, 21))
        self.label_19.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.label_19.setObjectName("label_19")
        self.comboBox_12 = QtWidgets.QComboBox(Dialog)
        self.comboBox_12.setGeometry(QtCore.QRect(550, 410, 91, 31))
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_13 = QtWidgets.QComboBox(Dialog)
        self.comboBox_13.setGeometry(QtCore.QRect(550, 510, 91, 32))
        self.comboBox_13.setObjectName("comboBox_13")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(550, 389, 81, 21))
        self.label_20.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(470, 350, 431, 41))
        self.label_21.setStyleSheet("font: 25pt \".SF NS Text\";")
        self.label_21.setObjectName("label_21")
        self.comboBox_14 = QtWidgets.QComboBox(Dialog)
        self.comboBox_14.setGeometry(QtCore.QRect(550, 560, 91, 32))
        self.comboBox_14.setObjectName("comboBox_14")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(680, 420, 151, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(690, 460, 101, 21))
        self.label_22.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.label_22.setObjectName("label_22")
        self.textEdit_3 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_3.setGeometry(QtCore.QRect(690, 480, 101, 21))
        self.textEdit_3.setObjectName("textEdit_3")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(680, 530, 141, 31))
        self.pushButton_7.setObjectName("pushButton_7")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "            London Stocks"))
        self.label_2.setText(_translate("Dialog", "                  Calculate Average Stock Price"))
        self.label_3.setText(_translate("Dialog", "Stock:"))
        self.label_4.setText(_translate("Dialog", "Start Year:"))
        self.label_5.setText(_translate("Dialog", "End Year:"))
        self.pushButton.setText(_translate("Dialog", "Calculate"))
        self.label_6.setText(_translate("Dialog", "Value:"))
        self.label_7.setText(_translate("Dialog", "                      Graphic Visualization"))
        self.label_8.setText(_translate("Dialog", "Start Year:"))
        self.label_9.setText(_translate("Dialog", "End Year:"))
        self.label_10.setText(_translate("Dialog", "Stock:"))
        self.pushButton_2.setText(_translate("Dialog", "Graph Data"))
        self.label_11.setText(_translate("Dialog", "                  Calculate Correlation"))
        self.label_12.setText(_translate("Dialog", "Start Year:"))
        self.label_13.setText(_translate("Dialog", "End Year:"))
        self.label_14.setText(_translate("Dialog", "Stock:"))
        self.label_15.setText(_translate("Dialog", "Stock:"))
        self.pushButton_3.setText(_translate("Dialog", "Calculate Correlation"))
        self.label_16.setText(_translate("Dialog", "Value:"))
        self.pushButton_4.setText(_translate("Dialog", "Graph Data"))
        self.pushButton_5.setText(_translate("Dialog", "Graph Related Data"))
        self.label_17.setText(_translate("Dialog", "Stock:"))
        self.label_18.setText(_translate("Dialog", "End Year:"))
        self.label_19.setText(_translate("Dialog", "Start Year:"))
        self.label_20.setText(_translate("Dialog", "Stock:"))
        self.label_21.setText(_translate("Dialog", "        Predict Future Average Stock Price"))
        self.pushButton_6.setText(_translate("Dialog", "Calculate"))
        self.label_22.setText(_translate("Dialog", "Value:"))
        self.pushButton_7.setText(_translate("Dialog", "Graph Data"))

