# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stock.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1012, 535)
        Dialog.setStyleSheet("")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(30, 70, 151, 26))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 461, 41))
        self.label.setStyleSheet("font: 26pt \"Georgia\";")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(140, 160, 113, 41))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(30, 120, 151, 21))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 290, 321, 41))
        self.label_2.setStyleSheet("font: 25pt \"Georgia\";")
        self.label_2.setObjectName("label_2")
        self.comboBox_3 = QtWidgets.QComboBox(Dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(30, 350, 151, 26))
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 50, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 330, 81, 16))
        self.label_5.setObjectName("label_5")
        self.comboBox_5 = QtWidgets.QComboBox(Dialog)
        self.comboBox_5.setGeometry(QtCore.QRect(250, 350, 151, 26))
        self.comboBox_5.setObjectName("comboBox_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(250, 330, 71, 20))
        self.label_6.setObjectName("label_6")
        self.comboBox_6 = QtWidgets.QComboBox(Dialog)
        self.comboBox_6.setGeometry(QtCore.QRect(250, 400, 151, 26))
        self.comboBox_6.setObjectName("comboBox_6")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(250, 380, 60, 16))
        self.label_8.setObjectName("label_8")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 450, 141, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(850, 170, 161, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(540, 170, 161, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(550, 280, 431, 41))
        self.label_11.setStyleSheet("font: 25pt \"Georgia\";")
        self.label_11.setObjectName("label_11")
        self.comboBox_7 = QtWidgets.QComboBox(Dialog)
        self.comboBox_7.setGeometry(QtCore.QRect(610, 340, 151, 26))
        self.comboBox_7.setObjectName("comboBox_7")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(610, 320, 81, 16))
        self.label_12.setObjectName("label_12")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(790, 320, 60, 16))
        self.label_15.setObjectName("label_15")
        self.comboBox_10 = QtWidgets.QComboBox(Dialog)
        self.comboBox_10.setGeometry(QtCore.QRect(790, 340, 161, 31))
        self.comboBox_10.setObjectName("comboBox_10")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(630, 400, 131, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(780, 400, 131, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(630, 10, 311, 41))
        self.label_16.setStyleSheet("font: 25pt \"Georgia\";")
        self.label_16.setObjectName("label_16")
        self.comboBox_11 = QtWidgets.QComboBox(Dialog)
        self.comboBox_11.setGeometry(QtCore.QRect(570, 70, 151, 26))
        self.comboBox_11.setObjectName("comboBox_11")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(570, 50, 81, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(570, 100, 81, 16))
        self.label_18.setObjectName("label_18")
        self.comboBox_12 = QtWidgets.QComboBox(Dialog)
        self.comboBox_12.setGeometry(QtCore.QRect(570, 120, 151, 26))
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_13 = QtWidgets.QComboBox(Dialog)
        self.comboBox_13.setGeometry(QtCore.QRect(780, 70, 151, 26))
        self.comboBox_13.setObjectName("comboBox_13")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(780, 50, 91, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(780, 100, 81, 16))
        self.label_20.setObjectName("label_20")
        self.comboBox_14 = QtWidgets.QComboBox(Dialog)
        self.comboBox_14.setGeometry(QtCore.QRect(780, 120, 151, 31))
        self.comboBox_14.setObjectName("comboBox_14")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(700, 170, 161, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(730, 150, 60, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(730, 380, 111, 21))
        self.label_22.setObjectName("label_22")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(220, 70, 151, 26))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(220, 50, 71, 16))
        self.label_4.setObjectName("label_4")
        self.comboBox_15 = QtWidgets.QComboBox(Dialog)
        self.comboBox_15.setGeometry(QtCore.QRect(220, 120, 151, 26))
        self.comboBox_15.setObjectName("comboBox_15")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(220, 100, 60, 16))
        self.label_10.setObjectName("label_10")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(30, 100, 60, 16))
        self.label_23.setObjectName("label_23")
        self.comboBox_4 = QtWidgets.QComboBox(Dialog)
        self.comboBox_4.setGeometry(QtCore.QRect(380, 120, 141, 31))
        self.comboBox_4.setObjectName("comboBox_4")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(400, 100, 47, 13))
        self.label_7.setObjectName("label_7")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(540, 240, 121, 21))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(540, 220, 111, 20))
        self.label_9.setObjectName("label_9")
        self.textEdit_3 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_3.setGeometry(QtCore.QRect(790, 450, 111, 16))
        self.textEdit_3.setObjectName("textEdit_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Calculate Average Stock Price"))
        self.pushButton.setText(_translate("Dialog", "Calculate"))
        self.label_2.setText(_translate("Dialog", "Graphic Visualization"))
        self.label_3.setText(_translate("Dialog", "Stock"))
        self.label_5.setText(_translate("Dialog", "Stock"))
        self.label_6.setText(_translate("Dialog", "Start Year"))
        self.label_8.setText(_translate("Dialog", "End Year"))
        self.pushButton_2.setText(_translate("Dialog", "Graph  Data"))
        self.pushButton_3.setText(_translate("Dialog", "Graph Related Data"))
        self.pushButton_4.setText(_translate("Dialog", "Calculate Correlation"))
        self.label_11.setText(_translate("Dialog", "Predict Future Average Stock Price"))
        self.label_12.setText(_translate("Dialog", "Stock 1"))
        self.label_15.setText(_translate("Dialog", "future year"))
        self.pushButton_5.setText(_translate("Dialog", "Graph"))
        self.pushButton_6.setText(_translate("Dialog", "Calculate"))
        self.label_16.setText(_translate("Dialog", "Calculate Correlation"))
        self.label_17.setText(_translate("Dialog", "Stock 1:"))
        self.label_18.setText(_translate("Dialog", "Stock 2:"))
        self.label_19.setText(_translate("Dialog", "Start Year"))
        self.label_20.setText(_translate("Dialog", "End Year"))
        self.pushButton_7.setText(_translate("Dialog", "Graph Data"))
        self.label_21.setText(_translate("Dialog", "TextLabel"))
        self.label_22.setText(_translate("Dialog", "Visual Representations"))
        self.label_4.setText(_translate("Dialog", "Start Year"))
        self.label_10.setText(_translate("Dialog", "End Year"))
        self.label_23.setText(_translate("Dialog", "Value"))
        self.label_7.setText(_translate("Dialog", "Column"))
        self.label_9.setText(_translate("Dialog", "Correlation Coefficient"))

